### ISSUE TITLE
Please clarify if Raspberry Pi OS (Legacy) can still be used

### ISSUE THREAD

**Issue by HorstBaerbel** [nicokaiser/rpi-audio-receiver#113]
The RPi foundation released a [backwards-compatible version of Raspbian / Raspberry Pi OS called "Legacy"](https://www.raspberrypi.com/software/operating-systems/), based on Debian "Buster". Can this be used together with rpi-audio-receiver (bluealsa package etc.)? Would be good to have that info in the README.

**Comment by nicokaiser** [comment]
There is a `debian-10` branch that still runs on Raspberry Pi OS 10 (the "Legacy" version). 

Newer updates of this repository will only work with the latest version (Raspberry Pi OS 11), with PulseAudio instead of BlueALSA. (This may or may not work on slower devices like Raspberry Pi 1 or Pi Zero)

**Comment by HorstBaerbel** [comment]
Thanks for the info. A hint in the README couldn't hurt...
