### ISSUE TITLE
Will volumio be supported?

### ISSUE THREAD

**Issue by HolyMacarony** [nicokaiser/rpi-audio-receiver#127]
I just tried to use this script to add BT support for the latest volumio but there are severaly changes in the volumio OS that make it impossible it seems.
Certain dependencies won't resolve and rapsi-config does not exist aswell.
So i would like to ask whether there is a way to incorporate this feature into volumio free? (paid plan offers it)

thank you very much

**Comment by nicokaiser** [comment]
Hello @HolyMacarony. Sorry, I cannot support other platforms than the current Raspberry Pi OS. Volumio 3 seems to be based on Debian Buster, so maybe the `debian-10` branch of this repository might help (it uses ALSA instead of PulseAudio), but you need to thoroughly look at the scripts and know exactly what you are doing in order not to break something. I have no idea if this can work at all, since Volumio and Raspi OS seem to have diverged...
