### ISSUE TITLE
useful option for install-spotify.sh if Raspberry Zero W is used

### ISSUE THREAD

**Issue by hilope** [nicokaiser/rpi-audio-receiver#145]
The script works like a charm and was the only way to get raspotify and shairport working on my Pi Zero W.
But for raspotify an old version has to be installed because ARMv6 is not supported anymore.

So if you add an option in install-spotify.sh that asks for a Pi Zero, the old version as described under https://github.com/dtcooper/raspotify/wiki/Raspotify-on-Pi-v1's-and-Pi-Zero-v1.x can be used for download instead of the actual version.

Pi Zero users will be happy.  ;)

**Comment by nicokaiser** [comment]
Thanks for the link.

Supporting the Pi Zero (and the Pi 1) is quite hard, since their hardware is not really capable of playing decent audio, and even less over Bluetooth or Wi-Fi. I tried to use a Pi Zero for AirPlay or Spotify, but each and every problem (performance, audio quality, network connections, Bluetooth stability) was solved by upgrading to a faster board like the Pi 3 or 4. 
I guess this is why raspotify also stopped supporting ARMv6.

While it is technically possible to use older raspotify versions on an ARMv6 board, I cannot really provide support for these combinations (it is hard enough to update the guide for "current Raspbian on current hardware", since the Raspberry Pi project tends to change things from time to time, especially the hardware-related things for audio and Bluetooth...
