### ISSUE TITLE
Bluetooth audio delay

### ISSUE THREAD

**Issue by giovi321** [nicokaiser/rpi-audio-receiver#171]
I know it is normal and I expected it: is there any way to reduce the audio delay over bluetooth?
Is there a way to debug this? Maybe decreasing audio quality?
Thanks!

**Comment by nicokaiser** [comment]
As far as I know, the delay is about 250ms, which should be barely noticeable. 
You can try to play with different values for bluealsa-aplay (by adding a systemd override):
https://github.com/Arkq/bluez-alsa/issues/156
… but I do not have any experience in this, it is beyond the scope of this project.

If you need better latency, you might be better off with better protocols like AirPlay (which has a much higher latency, but since clients "know" the latency the can accommodate for it).
