### ISSUE TITLE
Low Volume

### ISSUE THREAD

**Issue by valix85** [nicokaiser/rpi-audio-receiver#33]
Hi, everytime system up I need to connect it via ssh and set volume with this command

`amixer sset 'PCM' 96%`

It's possible save this settings or automate it?

thank you

**Comment by MattCosturos** [comment]
You could probably add that line to   /usr/local/bin/bluetooth-udev 
That script is called every time a device connects/disconnects.

**Comment by docgloucester** [comment]
There's a way to save your alsamixer config.
When you're done tweaking your volume levels the way you want, just run 
`sudo alsactl store`
and they will be saved.

**Comment by nicokaiser** [comment]
Thanks @docgloucester. Yes, `alsactl store` will store the current volume.

I did not add this to the installation script because some users may want to use an external device (USB or I2S) for much improved audio quality – and then they need to reboot the system before begin able to set the volume (And, the mixer may not be called "PCM" then, so setting the volume on startup would also not work).
