### ISSUE TITLE
no analog audio

### ISSUE THREAD

**Issue by lenschgo** [nicokaiser/rpi-audio-receiver#56]
It seems that the analog audio jacket is not linked to the DAC. I tried multiple boards and installations but none of these tries were sucessesful. There is no sound from the analog audio jacket of the pi. If i connect HDMI Connector with external audio jacket i get always sound from this source. Doesn't metter if i select Analog or HDMI for output. Also Alsamixer only shows as device "bcm2835 Headphones" or "bcm2835 HDMI 1" . Also if i look in "raspi-config" "audio" i cannot see my "3.5mm Jack" only "HDMI 1" and " Headphones" are listet.

**Comment by jonas-fischer** [comment]
I had the exact same problem. For me, the problem was that the install.sh script automatically upgrades all packages. Turns out the package 'raspberrypi-kernel' was the culprit. I don't know what specifically was the problem but 

downgrading the kernel from 4.19.118-v7l+ to 4.19.97-v7l+ 

resolved the issue. Now I have back contol over the audio output and toggle between HDMI and 3.5mm. I don't know if other version work but this worked in my backup so I downgraded to 97.
To downgrade I used this guide 
https://isahatipoglu.com/2015/09/29/how-to-upgrade-or-downgrade-raspberrypis-kernel-servoblaster-problem-raspberry-pi2/
