### ISSUE TITLE
[Feature Request] Add support for better bluetooth codecs AAC and aptx (HD)

### ISSUE THREAD

**Issue by MKSounds** [nicokaiser/rpi-audio-receiver#62]
Hi @nicokaiser ,
really nice project and exactly what I was searching for.

I did a bit of research if it is possible to use the higher-quality codecs aac and aptx for bluetooth audio.
I found out, that it is possible to use those codecs as an install option of BlueALSA: [https://github.com/Arkq/bluez-alsa](url).
With the arguments --enable-aac, --enable-aptx, --enable-aptx-hd it should be possible to use the better quality codecs, because SBC codec is more like a compromise solution.

Or is that feature already integrated? I didn't find any hints in the description.
Kind regards,
Markus

**Comment by nicokaiser** [comment]
Thanks for your suggestion!

This project is meant to be as simple as possible and as close to the original Debian/Raspbian (Raspberry Pi OS) packages. The Raspbian package is bluealsa 1.4.0 currently, and it is compiled without AAC and APTX support unfortunately (this might be due to licensing issues, but I'm not sure about this).

As compiling bluez-alsa requires a lot of development libraries, I avoid this in this case and leave this to individual enhancements...
